### ISSUE TITLE
Export helper doesn't generate file

### ISSUE THREAD

**Issue by jonbstrong** [keremtiryaki/Slack-Api-Helpers#1]
When using the export helper (https://cdn.rawgit.com/trototype/Slack-Api-Helpers/master/public/index.html), I am able to generate the list of private groups using the token, but after clicking "get history", the loading bar appears and no log/file is generated.

https://www.dropbox.com/s/z2nvznu0lqmkb3a/Screenshot%202015-09-04%2017.42.41.png?dl=0

**Comment by keremtiryaki** [comment]
i think, i fixed the problem. Please check it out again.
The rawgit CDN is not updating the content immediately.
So i changed the url: 
https://s3-eu-west-1.amazonaws.com/trototype-website/index.html

**Comment by jonbstrong** [comment]
Cool. So it's now retrieving content but it doesn't seem to go back in the archives further than the current conversation (what you can already see in slack)

**Comment by keremtiryaki** [comment]
slack api is not providing archived data right now.
